Crear componente de sub-navegación dentro de la sección de "Usuarios"
juanpernu/BilogWeb pull request #24
Opened 2021-01-11 16:04 UTC by RodriJOk

Se agrego el nuevo componente de la seccion usuarios, juntos con las card.

2021-01-12 13:04 UTC, juanpernu commented on components/Card/Card.js
> +
Delete space

2021-01-12 13:05 UTC, juanpernu commented on components/CardUser/CardUser.js
> +const CardUser = ({title, img, url})=>{
```suggestion
const CardUser = ({title, img, url}) => {
```

2021-01-12 13:17 UTC, juanpernu commented on components/CardUser/CardUser.js
> +        <Link href={`${url}`}>
Esto es lo mismo que hacer `<Link href={url}>`

2021-01-12 13:17 UTC, juanpernu commented on components/CardUser/CardUser.js
> +                    <img src="../static/bilog-arrow-down.svg" />
👍

2021-01-12 13:20 UTC, juanpernu commented on components/CardUser/CardUser.js
> +                margin: 1.5em 0.7em;
Espectacular las medidas relativas, pero en el caso del `margin` generalmente lo mejor es tener medidas fijas (px).

2021-01-12 13:23 UTC, juanpernu commented on components/CardUser/CardUser.js
> +
Delete space

2021-01-12 13:24 UTC, juanpernu commented on components/CardUser/CardUser.js
> +                margin: 0px 0.7em;
Idem al comment del `margin` anterior

2021-01-12 13:24 UTC, juanpernu commented on components/CardUser/CardUser.js
> +                background:white;
```suggestion
                background-color: white;
```

2021-01-12 13:26 UTC, juanpernu commented on components/CardUser/CardUser.js
> +                color:#333333;
```suggestion
                color:#333;
```
Cuando los valores hexa se repiten de esa forma, se puede abreviar con los 3 numeros.

2021-01-12 13:27 UTC, juanpernu commented on components/CardUser/CardUser.js
> +                color:#333333;
Idem comentario anterior

2021-01-12 13:27 UTC, juanpernu commented on components/CardUser/CardUserList.js
> +const CardListData = [
Está perfecta esta estructura, solamente la llevaría al folder `/mocks` y crearía un archivo nuevo que puedas consumirlo desde este componente

2021-01-12 13:29 UTC, juanpernu commented on components/Column.js
>                </Link>
En este caso, como el componente `<Link>` engloba al tag `<a>`, no es necesario agregarle el `key` al `<a>` porque ya lo tiene el `<Link>`

2021-01-12 13:31 UTC, juanpernu commented on pages/users.js
> +    <CardUserList/>
Lo ideal, en cuanto al renderizado de la data, sería que ese JSON con los items a renderizar se le pasen al componente desde acá. Por ahora no es necesario que lo encaremos así, pero de esa forma volvemos agnostico al componente hijo. Después lo vemos mas en profundidad 😉

2021-01-12 13:31 UTC, juanpernu approved these changes

2021-01-13 20:01 UTC, DidierSoules approved these changes

2021-01-14 13:49 UTC, juanpernu requested changes
El package-lock habría que sacarlo. Solamente lo pusheamos cuando instalamos dependencias nuevas, en este caso no instalamos dependencias nuevas por lo que habría que sacarlo. Puede llegar a traer conflictos a futuro.

2021-01-16 21:34 UTC, juanpernu commented on components/CardUser/CardUser.js
> +                text-align: center;
Acá podríamos agregarle: `transition: all .3s ease;` para que el hover sea más "suave".

2021-01-16 21:35 UTC, juanpernu commented on components/CardUser/CardUser.js
> +                background: #fff;
Acá podríamos agregarle: `transition: all .3s ease;` para que el hover sea más "suave". En mobile no porque no tenemos la interacción `:hover`.

2021-01-18 18:27 UTC, DidierSoules approved these changes

2021-01-18 19:52 UTC, juanpernu approved these changes

2021-01-18 19:54 UTC, merged