Se creo sub-sección/vista "Documentación"
juanpernu/BilogWeb pull request #25
Opened 2021-01-12 18:28 UTC by RodriJOk

Se creo la nueva sub seccion/vista Documentacion para que dentro de la seccion "Usuarios", se pueda acceder a ella.

2021-01-14 13:46 UTC, juanpernu commented on next.config.js
> +      '/users/document':{page: 'document'}
Esta ruta debería ser: `'/document':{ page: 'document' }` independientemente que se acceda desde la ruta `/users`

2021-01-14 13:46 UTC, juanpernu requested changes
Habría que cambiar la ruta del build de la pages /documents

2021-01-18 18:48 UTC, juanpernu commented on next.config.js
> +      '/document':{page: 'document'}
/document/index

2021-01-18 21:52 UTC, DidierSoules approved these changes

2021-01-19 12:03 UTC, juanpernu approved these changes

2021-01-19 12:19 UTC, merged