Creacion de la estructura JSON
juanpernu/BilogWeb pull request #27
Opened 2021-01-15 13:32 UTC by RodriJOk

Creacion de la pagina docs.js, dentro de la carpeta mocks, en la cual se crea un estructura JSON con la informacion sobre caracteristicas y funcionalidades de Bilog Software

2021-01-16 20:12 UTC, juanpernu commented on mocks/docs.js
> +          image:'https://youtu.be/c98oEfmindU',
Ojo que esto es un video. Este objeto debería tener una propiedad que sea `video` con la URL. Si vamos por ese approach, hay que agregarlo en todos los otros `featureContent` para mantener la consistencia.

Después, el componente que lo renderize tiene que ser inteligente para mostrarlo o no.

2021-01-16 20:13 UTC, juanpernu commented on mocks/docs.js
> +          image:'https://youtu.be/c98oEfmindU',
Idem comment arriba

2021-01-16 20:15 UTC, juanpernu requested changes
Todas las `featureContent` tienen un link a youtube en la prop `image`. Habría que crear una nueva que se llame `video` y replicarlos en todos. Los que no tengan video, irá la propiedad con value `false`.

2021-01-18 16:55 UTC, juanpernu approved these changes

2021-01-18 17:07 UTC, DidierSoules approved these changes

2021-01-18 17:12 UTC, merged