Create an accordion component that reads data from the JSON and renders it (BILW-009)
juanpernu/BilogWeb pull request #28
Opened 2021-01-15 13:41 UTC by DidierSoules

Made an accordion component which reads data from the faqs JSON and renders it at /faqs .
Fixed its styles.

2021-01-16 20:20 UTC, juanpernu commented on components/Faq/index.js
> +                  padding 15px 30px 15px 30px;
Una boludez, pero esto puede ser: `padding: 15px 30px`

2021-01-16 20:20 UTC, juanpernu approved these changes

2021-01-17 13:51 UTC, juanpernu commented on components/Faq/FAQ.js
> +              text-align: left;
`font-size: 18px`

2021-01-17 13:51 UTC, juanpernu commented on components/Faq/FAQ.js
> +              font-size: 20px;
```suggestion
              font-size: 18px;
```

2021-01-17 13:53 UTC, juanpernu commented on components/Faq/index.js
> +                  width: 50%;
```suggestion
                  max-width: 646px;
```

2021-01-17 13:53 UTC, juanpernu commented on components/Faq/index.js
> +                  margin: 0 auto;
Agregar `max-width: 646px;`

2021-01-17 13:54 UTC, juanpernu commented on components/Faq/FAQ.js
> +              width: 20px;
```suggestion
              width: 15px;
```

2021-01-17 13:54 UTC, juanpernu commented on components/Faq/FAQ.js
> +              width: 20px;
```suggestion
              width: 15px;
```

2021-01-17 13:56 UTC, juanpernu commented on components/Faq/FAQ.js
> +              transition: all 0.2s ease-out;
`font-size: 14px;`

2021-01-17 13:57 UTC, juanpernu commented on components/Faq/FAQ.js
> +              transition: all 0.4s ease-out;
`font-size: 14px;`

2021-01-17 13:59 UTC, juanpernu commented on components/Faq/FAQ.js
> +              padding-top: 10px;
```suggestion
              padding-top: 20px;
```

2021-01-17 13:59 UTC, juanpernu commented on components/Faq/FAQ.js
> +              padding-top: 10px;
```suggestion
              padding-top: 20px;
```

2021-01-17 14:01 UTC, juanpernu commented on components/Faq/FAQ.js
> +              box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
Para empatar la sombra con los demás componentes
```suggestion
              box-shadow: 0px 10px 30px rgba(0,0,0,0.12);
```

2021-01-17 14:01 UTC, juanpernu commented on components/Faq/FAQ.js
> +              box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
Para empatar la sombra con los demás componentes
```suggestion
              box-shadow: 0px 10px 30px rgba(0,0,0,0.12);
```

2021-01-17 14:05 UTC, juanpernu commented on components/Faq/FAQ.js
> +              padding: 15px;
```suggestion
              padding: 32px;
```

2021-01-17 14:05 UTC, juanpernu commented on components/Faq/FAQ.js
> +              padding: 15px;
```suggestion
              padding: 32px;
```

2021-01-17 14:05 UTC, juanpernu requested changes
Dejo algunos comments para empatar los estilos con los de la referencia de mercado pago! Lo demás lo veo super ok

2021-01-18 16:59 UTC, juanpernu approved these changes

2021-01-18 17:04 UTC, juanpernu approved these changes

2021-01-18 17:05 UTC, RodriJOk approved these changes

2021-01-18 17:12 UTC, merged