Rename section for "Centro de clientes" (BILW-027)
juanpernu/BilogWeb pull request #29
Opened 2021-01-15 19:17 UTC by DidierSoules

Corrected some typos.

2021-01-16 20:25 UTC, juanpernu commented on components/Menu/Desktop.js
>            <Link href="/users">
Acá, con el cambio del name, habría que renombrar el link por `/customer-area`.

2021-01-16 20:25 UTC, juanpernu commented on components/Menu/Mobile.js
>            <Link href="/users">
Acá, con el cambio del name, habría que renombrar el link por `/customer-area`.

2021-01-16 20:26 UTC, juanpernu requested changes
Al renombrar el link por `/customer-area`, tenemos que cambiar el nombre de la page en el folder `pages` y también cambiar la ruta en el export en el file `now.config.js`.

Estaría bueno volver a subirlo a test para poder probar que siga funcionando todo de forma correcta.

2021-01-18 15:21 UTC, juanpernu approved these changes

2021-01-18 15:27 UTC, RodriJOk approved these changes

2021-01-18 15:56 UTC, merged