Creation of the accordion component and adjustments of the styles in mobile and desktop (BILW-049)
juanpernu/BilogWeb pull request #72
Opened 2021-03-03 18:21 UTC by RodriJOk

Styles from desktop. 
![2021-03-03 (9)](https://user-images.githubusercontent.com/46611601/109852234-54093d00-7c33-11eb-99b4-84f4b7723836.png)

Styles from mobile
![2021-03-03 (11)](https://user-images.githubusercontent.com/46611601/109852568-a8acb800-7c33-11eb-9da9-a0633c42c2fd.png)

2021-03-03 18:42 UTC, DidierSoules requested changes

2021-03-03 18:42 UTC, DidierSoules commented on components/Accordion/Accordion.js
> +const Accordion = ({text, childrens, onClick}) =>{
Cambiar `childrens` por `children` .

2021-03-03 18:42 UTC, DidierSoules commented on components/Accordion/Accordion.js
> +            {childrens.map(child => {
Cambiar `childrens` por `children` .

2021-03-03 18:42 UTC, DidierSoules commented on components/Docs/SidebarSection.js
>  const SidebarSection = ({ text, hash, onClickHandler, childrens }) => {
Cambiar `childrens` por `children` .

2021-03-03 18:42 UTC, DidierSoules commented on components/Docs/SidebarSection.js
> +        <Accordion classname="acordion"text={text} childrens={childrens} onClick={handleOnClick} />
Cambiar `childrens` por `children` .

2021-03-03 19:16 UTC, juanpernu commented on components/Accordion/Accordion.js
> +                font-size:12px;
```suggestion
                font-size:16px;
```

2021-03-03 19:21 UTC, juanpernu commented on components/Accordion/Accordion.js
> +                justify-content: space-between;
```suggestion
                justify-content: flex-start;
```

2021-03-03 19:21 UTC, juanpernu commented on components/Accordion/Accordion.js
> +                margin:5px;
```suggestion
                margin: 5px 0 5px 20px;
```

2021-03-03 19:22 UTC, juanpernu commented on components/Accordion/Accordion.js
> +                justify-content: space-between;
```suggestion
                justify-content: flex-start;
```

2021-03-03 19:23 UTC, juanpernu commented on components/Accordion/Accordion.js
> +                margin:5px;
```suggestion
                margin: 5px 0 5px 20px;
```

2021-03-03 19:24 UTC, juanpernu commented on components/Accordion/Accordion.js
> +              }
```suggestion
              .submenu-item:hover{
                color: #000;
                cursor: pointer;
              }
```

2021-03-03 19:26 UTC, juanpernu commented on components/Accordion/Accordion.js
> +const Accordion = ({text, childrens, onClick}) =>{
Si bien es un typo, childrens es un array de objetos, por eso el plural. Pero es a gusto del consumidor 😛

2021-03-03 21:06 UTC, DidierSoules commented on components/Accordion/Accordion.js
> +const Accordion = ({text, childrens, onClick}) =>{
Hmm ok no sabia, pero pasa que la palabra childrens no existe jaja. Pero bueno como ustedes prefieran :D

2021-03-03 21:12 UTC, DidierSoules approved these changes

2021-03-08 23:20 UTC, juanpernu commented on components/Accordion/Accordion.js
> +const Accordion = ({text, childrens, onClick}) =>{
@DidierSoules jajajaja buen punto!

2021-03-08 23:21 UTC, juanpernu approved these changes

2021-03-09 11:32 UTC, merged