Creation of the versions component on the page /first-steps
juanpernu/BilogWeb pull request #83
Opened 2021-03-25 12:49 UTC by RodriJOk

Component in Desktop 👇🖥 
![2021-03-25 (1)](https://user-images.githubusercontent.com/46611601/112475060-26557680-8d4f-11eb-987c-58774229dd88.png)

Component in Mobile 👇📱 
![2021-03-25 (3)](https://user-images.githubusercontent.com/46611601/112475136-3e2cfa80-8d4f-11eb-932f-d49367306a17.png)

2021-03-25 17:04 UTC, DidierSoules requested changes

2021-03-25 17:04 UTC, DidierSoules commented on components/CardFirstSteps/ContainerCardFirstSteps.js
> +                title="Small "
title="Small " -> title="Small" :D

2021-03-26 16:19 UTC, DidierSoules approved these changes

2021-03-29 16:12 UTC, juanpernu commented on components/CardFirstSteps/CardFirstSteps.js
> +          {external ? renderExternalLink() : null}
Esto puede ser: `external && renderExternalLink()`

2021-06-21 13:10 UTC, DidierSoules approved these changes

2021-10-13 14:54 UTC, juanpernu commented on components/FirstSteps/CardFirstSteps/index.js
> +};
Para que quede en una sola linea, esto puede ser:

```
const CardFirstSteps = ({ children, className = "" }) => <div className={`${className}`}>{children}</div>;
```

Pero es solamente un detalle

2021-10-13 15:00 UTC, juanpernu commented on components/FirstSteps/index.module.scss
> +      }
Muy bien esto 👏

2021-10-13 18:34 UTC, merged